# Generated by Django 5.2.4 on 2025-10-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_address',
            field=models.TextField(blank=True, help_text='Complete business address for invoices', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='business_name',
            field=models.CharField(blank=True, help_text='Business/Shop name (appears on invoices)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_at',
            field=models.DateTimeField(blank=True, help_text='Last login timestamp', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_completed',
            field=models.BooleanField(default=False, help_text='Has user completed profile setup'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_status',
            field=models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='trial', help_text='Current subscription status', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, help_text='When trial period ends', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gstin',
            field=models.CharField(blank=True, help_text='GST Identification Number (optional)', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(help_text='Phone number for login recovery and communication', max_length=15, unique=True),
        ),
    ]
