# Generated by Django 5.2.4 on 2026-02-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_actionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_lifetime_free',
            field=models.BooleanField(default=False, help_text='Account is permanently free (VIP/Friends)'),
        ),
    ]
