# Generated by Django 5.2.4 on 2026-02-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_is_lifetime_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('salesman', 'Salesman'), ('accountant', 'Accountant')], default='admin', help_text='User capability role', max_length=20),
        ),
    ]
