# Generated by Django 5.2.4 on 2026-03-03 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='permissions',
            field=models.JSONField(blank=True, default=dict, help_text='Granular permissions for managers'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_tier',
            field=models.CharField(choices=[('FREE', 'Free'), ('MID', 'Mid'), ('PRO', 'Pro')], default='FREE', help_text='Subscription tier for limits', max_length=10),
        ),
    ]
