# Generated by Django 5.2.4 on 2026-03-03 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_parent_user_permissions_user_subscription_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number for login recovery and communication', max_length=15, null=True, unique=True),
        ),
    ]
