# Generated by Django 5.2.4 on 2026-04-27 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_gem_id_dl_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, help_text='City/Town', max_length=100, null=True),
        ),
    ]
