# Generated by Django 5.2.4 on 2026-05-18 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(choices=[('IN', 'India'), ('AE', 'United Arab Emirates')], default='IN', help_text='Active country for the shop', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='currency',
            field=models.CharField(choices=[('INR', 'Indian Rupee (₹)'), ('AED', 'UAE Dirham (د.إ)')], default='INR', help_text='Active currency for the shop', max_length=3),
        ),
        migrations.AddField(
            model_name='user',
            name='is_vat_registered',
            field=models.BooleanField(default=False, help_text='Is the business VAT registered? (for UAE)'),
        ),
        migrations.AddField(
            model_name='user',
            name='trn',
            field=models.CharField(blank=True, help_text='Tax Registration Number (15-digit for UAE)', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gstin',
            field=models.CharField(blank=True, help_text='GST Identification Number (optional, for India)', max_length=15, null=True),
        ),
    ]
