# Generated by Django 5.2.4 on 2026-05-18 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_country_user_currency_user_is_vat_registered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, help_text='State/Region for tax calculation (Place of Supply)', max_length=50, null=True),
        ),
    ]
