# Generated by Django 5.2.4 on 2026-05-31 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('salesman', 'Salesman'), ('accountant', 'Accountant'), ('hr', 'HR'), ('employee', 'Employee')], default='admin', help_text='User capability role', max_length=20),
        ),
    ]
