# Generated by Django 5.2.4 on 2026-09-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number for login recovery and communication', max_length=15, null=True),
        ),
    ]
