# Generated by Django 5.2.4 on 2026-09-28 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bank_account_number',
            field=models.CharField(blank=True, help_text='Bank account number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_branch',
            field=models.CharField(blank=True, help_text='Bank branch name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_ifsc_code',
            field=models.CharField(blank=True, help_text='Bank IFSC code', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Bank name for invoice payments', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_qr_code',
            field=models.TextField(blank=True, help_text='Base64 encoded or URL of payment QR code', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_upi_id',
            field=models.CharField(blank=True, help_text='UPI ID / VPA for payments', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pan_number',
            field=models.CharField(blank=True, help_text='PAN Number (optional, for India)', max_length=20, null=True),
        ),
    ]
