# Generated by Django 5.2.4 on 2026-10-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_bank_account_number_user_bank_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='quotation_prefix',
            field=models.CharField(default='QT-', help_text='Default quotation prefix for this user', max_length=20),
        ),
    ]
