# Generated by Django 5.2.4 on 2026-10-09 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_quotation_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='delivery_challan_prefix',
            field=models.CharField(default='DC-', help_text='Default delivery challan prefix for this user', max_length=20),
        ),
    ]
