# Generated by Django 5.2.4 on 2025-12-21 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_customer_created_at'),
        ('inventory', '0004_alter_product_stock_productbatch_warehouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebillitem',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Specific batch being purchased', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.productbatch'),
        ),
        migrations.AddField(
            model_name='salesinvoiceitem',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Specific batch being sold', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.productbatch'),
        ),
    ]
