# Generated by Django 5.2.4 on 2025-12-21 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_customer_allow_credit_customer_credit_limit_and_more'),
        ('inventory', '0004_alter_product_stock_productbatch_warehouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebill',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Warehouse where items are received', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Warehouse from where items are sold', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse'),
        ),
    ]
