# Generated by Django 5.2.4 on 2026-02-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_customer_state_salesinvoice_place_of_supply'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebillitem',
            name='free_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Qty received free under scheme'),
        ),
        migrations.AddField(
            model_name='salesinvoiceitem',
            name='free_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Qty given free under scheme (Buy X Get Y)'),
        ),
    ]
