# Generated by Django 5.2.4 on 2026-02-14 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_deliverychallan_deliverychallanitem_invoicesettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loyalty_points', models.PositiveIntegerField(default=0, help_text='Accrued loyalty points')),
                ('party_category', models.CharField(choices=[('retailer', 'Retailer'), ('wholesaler', 'Wholesaler'), ('distributor', 'Distributor'), ('consumer', 'End Consumer')], default='consumer', help_text='Classification for pricing and reporting', max_length=20)),
                ('credit_days', models.PositiveIntegerField(default=0, help_text='Default payment terms in days')),
                ('gst_type', models.CharField(choices=[('registered', 'Registered'), ('unregistered', 'Unregistered'), ('composite', 'Composite')], default='unregistered', max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta', to='billing.customer')),
            ],
        ),
    ]
