# Generated by Django 5.2.4 on 2026-02-14 20:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_partymeta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('irn', models.CharField(blank=True, help_text='Invoice Reference Number from NIC', max_length=100)),
                ('ack_number', models.CharField(blank=True, max_length=50)),
                ('ack_date', models.DateTimeField(blank=True, null=True)),
                ('signed_invoice', models.JSONField(blank=True, default=dict, help_text='Signed JSON from NIC')),
                ('qr_code_data', models.TextField(blank=True, help_text='QR code data string')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='e_invoice', to='billing.salesinvoice')),
            ],
        ),
        migrations.CreateModel(
            name='EWayBill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('eway_bill_number', models.CharField(blank=True, help_text='Generated e-way bill number', max_length=50)),
                ('vehicle_number', models.CharField(blank=True, max_length=20)),
                ('transporter_name', models.CharField(blank=True, max_length=100)),
                ('transporter_id', models.CharField(blank=True, help_text='GSTIN of transporter', max_length=20)),
                ('distance_km', models.PositiveIntegerField(default=0)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eway_bill', to='billing.salesinvoice')),
            ],
        ),
    ]
