# Generated by Django 5.2.4 on 2026-02-15 22:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_einvoice_ewaybill'),
        ('inventory', '0010_productmeta_crate_qty_productmeta_crate_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credit_note_number', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('reason', models.CharField(choices=[('return', 'Goods Returned'), ('defective', 'Defective Goods'), ('discount', 'Post-Sale Discount'), ('rate_diff', 'Rate Difference'), ('other', 'Other')], default='return', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='billing.customer')),
                ('original_invoice', models.ForeignKey(blank=True, help_text='Original invoice being credited', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes', to='billing.salesinvoice')),
                ('warehouse', models.ForeignKey(blank=True, help_text='Warehouse where returned goods are received', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='CreditNoteItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hsn_sac_code', models.CharField(blank=True, max_length=20, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.productbatch')),
                ('credit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.creditnote')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='DebitNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('debit_note_number', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('vendor_name', models.CharField(max_length=255)),
                ('vendor_gstin', models.CharField(blank=True, max_length=15, null=True)),
                ('reason', models.CharField(choices=[('return', 'Goods Returned'), ('defective', 'Defective Goods'), ('rate_diff', 'Rate Difference'), ('shortage', 'Short Supply'), ('other', 'Other')], default='return', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('original_bill', models.ForeignKey(blank=True, help_text='Original purchase bill being debited', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debit_notes', to='billing.purchasebill')),
                ('warehouse', models.ForeignKey(blank=True, help_text='Warehouse from where goods are returned', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='DebitNoteItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hsn_sac_code', models.CharField(blank=True, max_length=20, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.productbatch')),
                ('debit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.debitnote')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
            ],
        ),
    ]
