# Generated by Django 5.2.4 on 2026-04-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_vendor_purchasebill_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('final', 'Final')], default='final', max_length=20),
        ),
    ]
