# Generated by Django 5.2.4 on 2026-04-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0020_invoicesettings_item_toggles'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='round_off',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
