# Generated by Django 5.2.4 on 2026-05-18 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0025_purchaseorder_purchaseorderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(blank=True, help_text="Customer's State/Region (Determines Tax Treatment)", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='place_of_supply',
            field=models.CharField(blank=True, help_text='State/Region code where goods are supplied', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='state',
            field=models.CharField(blank=True, help_text="Vendor's State/Region (Determines Tax Treatment)", max_length=50, null=True),
        ),
    ]
