# Generated by Django 5.2.4 on 2026-09-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0026_alter_customer_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
