# Generated by Django 5.2.4 on 2026-09-21 12:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0027_salesorderitem_discount_salesorderitem_tax_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='creditnote',
            unique_together={('created_by', 'credit_note_number')},
        ),
        migrations.AlterUniqueTogether(
            name='debitnote',
            unique_together={('created_by', 'debit_note_number')},
        ),
    ]
