# Generated by Django 5.2.4 on 2026-09-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0028_alter_creditnote_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderitem',
            name='free_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
