# Generated by Django 5.2.4 on 2026-09-21 18:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0029_salesorderitem_free_quantity'),
        ('inventory', '0019_product_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(default='sales_invoice', max_length=50)),
                ('prefix', models.CharField(max_length=50)),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='salesinvoice',
            unique_together={('created_by', 'invoice_number')},
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['created_by', 'invoice_number'], name='billing_sal_created_eb3932_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['created_by', 'invoice_date'], name='billing_sal_created_c16f01_idx'),
        ),
        migrations.AddField(
            model_name='invoicesequence',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_sequences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='invoicesequence',
            index=models.Index(fields=['tenant', 'document_type', 'prefix'], name='billing_inv_tenant__207a67_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='invoicesequence',
            unique_together={('tenant', 'document_type', 'prefix')},
        ),
    ]
