# Generated by Django 5.2.4 on 2026-09-21 18:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def deduplicate_sales_invoices(apps, schema_editor):
    """
    Ensure any existing duplicate invoice numbers for the same tenant are gracefully
    renumbered (e.g. INV-001-DUP1) before applying the unique constraint.
    Prevents migration failures on production databases with pre-existing duplicates.
    """
    SalesInvoice = apps.get_model('billing', 'SalesInvoice')
    from django.db.models import Count

    duplicates = (
        SalesInvoice.objects.values('created_by', 'invoice_number')
        .annotate(cnt=Count('id'))
        .filter(cnt__gt=1)
    )

    for item in duplicates:
        created_by_id = item['created_by']
        inv_num = item['invoice_number']
        invoices = list(
            SalesInvoice.objects.filter(
                created_by_id=created_by_id,
                invoice_number=inv_num
            ).order_by('created_at', 'id')
        )
        for idx, inv in enumerate(invoices[1:], start=1):
            counter = idx
            prefix = inv_num if inv_num else "INV"
            new_num = f"{prefix}-DUP{counter}"
            while SalesInvoice.objects.filter(
                created_by_id=created_by_id,
                invoice_number=new_num
            ).exists():
                counter += 1
                new_num = f"{prefix}-DUP{counter}"
            inv.invoice_number = new_num
            inv.save(update_fields=['invoice_number'])


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0029_salesorderitem_free_quantity'),
        ('inventory', '0019_product_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(default='sales_invoice', max_length=50)),
                ('prefix', models.CharField(max_length=50)),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RunPython(deduplicate_sales_invoices, reverse_code=migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='salesinvoice',
            unique_together={('created_by', 'invoice_number')},
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['created_by', 'invoice_number'], name='billing_sal_created_eb3932_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['created_by', 'invoice_date'], name='billing_sal_created_c16f01_idx'),
        ),
        migrations.AddField(
            model_name='invoicesequence',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_sequences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='invoicesequence',
            index=models.Index(fields=['tenant', 'document_type', 'prefix'], name='billing_inv_tenant__207a67_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='invoicesequence',
            unique_together={('tenant', 'document_type', 'prefix')},
        ),
    ]
