# Generated by Django 5.2.4 on 2026-09-22 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0030_invoicesequence_alter_salesinvoice_unique_together_and_more'),
        ('inventory', '0019_product_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverychallan',
            name='converted_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_delivery_challans', to='billing.salesinvoice'),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='customer_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='customer_gstin',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='eway_bill_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='po_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='po_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='round_off',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('billed', 'Billed'), ('cancelled', 'Cancelled')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='transport_mode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Warehouse from where goods are dispatched', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='deliverychallanitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='deliverychallanitem',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Specific batch being dispatched', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.productbatch'),
        ),
        migrations.AddField(
            model_name='deliverychallanitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='deliverychallanitem',
            name='free_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Free/sample quantity dispatched'),
        ),
        migrations.AddField(
            model_name='deliverychallanitem',
            name='hsn_sac_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='deliverychallanitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='deliverychallanitem',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='deliverychallanitem',
            name='unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='deliverychallan',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.customer'),
        ),
        migrations.AlterField(
            model_name='deliverychallanitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='deliverychallan',
            index=models.Index(fields=['created_by', 'challan_number'], name='billing_del_created_a28e3f_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverychallan',
            index=models.Index(fields=['created_by', 'date'], name='billing_del_created_8b0d42_idx'),
        ),
    ]
