# Generated by Django 5.2.4 on 2026-09-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0031_deliverychallan_converted_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderitem',
            name='dispatched_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Quantity dispatched / fulfilled'),
        ),
    ]
