# Generated by Django 5.2.4 on 2026-09-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0032_salesorderitem_dispatched_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnoteitem',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Custom item description / note'),
        ),
        migrations.AddField(
            model_name='debitnoteitem',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Custom item description / note'),
        ),
        migrations.AddField(
            model_name='deliverychallanitem',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Custom item description / note'),
        ),
        migrations.AddField(
            model_name='purchasebillitem',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Custom item description / note'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Custom item description / note'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Custom item description / note'),
        ),
        migrations.AddField(
            model_name='salesinvoiceitem',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Custom item description / note'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Custom item description / note'),
        ),
    ]
