# Generated by Django 5.2.4 on 2026-09-25 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0033_creditnoteitem_description_debitnoteitem_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='source_quotation',
            field=models.ForeignKey(blank=True, help_text='Original quotation this order was converted from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='billing.quotation'),
        ),
        migrations.AlterField(
            model_name='deliverychallan',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('billed', 'Billed'), ('cancelled', 'Cancelled')], default='open', max_length=20),
        ),
    ]
