# Generated by Django 5.2.4 on 2026-09-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0034_add_source_quotation_to_sales_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverychallanitem',
            name='price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=14),
        ),
        migrations.AlterField(
            model_name='salesinvoiceitem',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=14),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=14),
        ),
    ]
