# Generated by Django 5.2.4 on 2026-09-28 18:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0036_add_row_type_and_nullable_product_to_items'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebill',
            name='gst_withheld_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount of GST withheld from vendor', max_digits=12),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='gst_withholding_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='gst_withholding_override',
            field=models.BooleanField(default=False, help_text='True if user manually bypassed withholding'),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='gstr2b_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('matched', '100% Matched in GSTR-2B'), ('probable_match', 'Probable Match (Fuzzy)'), ('missing_in_2b', 'Missing in GSTR-2B (At-Risk ITC)'), ('disputed_tax', 'Tax Discrepancy'), ('manual_override', 'Manually Approved')], default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='is_gst_withheld',
            field=models.BooleanField(default=False, help_text='True if GST amount is currently locked/withheld'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='compliance_score',
            field=models.IntegerField(default=100, help_text='Vendor GST Compliance Score (0-100)'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='default_withholding_enabled',
            field=models.BooleanField(default=True, help_text='Automatically hold GST on unmatched bills'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='last_reconciliation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='risk_tier',
            field=models.CharField(choices=[('safe', 'Safe / Trusted'), ('moderate_risk', 'Moderate Risk'), ('defaulter', 'High Risk / Defaulter')], default='safe', max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='total_at_risk_itc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='vendor',
            name='total_billed_itc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='vendor',
            name='total_reconciled_itc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='salesinvoiceitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='GSTR2BImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('return_period', models.CharField(help_text='e.g. 082026 or Aug-2026', max_length=20)),
                ('financial_year', models.CharField(default='2026-2027', max_length=20)),
                ('source', models.CharField(choices=[('file_upload', 'File Upload'), ('api_sync', 'Govt API Sync')], default='file_upload', max_length=20)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('total_invoices', models.PositiveIntegerField(default=0)),
                ('total_taxable_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_itc_available', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_igst', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_cgst', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_sgst', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_cess', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('matched_count', models.PositiveIntegerField(default=0)),
                ('probable_count', models.PositiveIntegerField(default=0)),
                ('missing_in_books_count', models.PositiveIntegerField(default=0)),
                ('reconciled_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reconciled_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorLegalNotice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notice_number', models.CharField(max_length=100, unique=True)),
                ('generated_date', models.DateField(auto_now_add=True)),
                ('period', models.CharField(help_text='e.g. Q1 2026 or Aug-2026', max_length=50)),
                ('total_unmatched_invoices', models.PositiveIntegerField(default=1)),
                ('total_invoiced_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_itc_claimed_back', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('statutory_deadline_date', models.DateField(help_text='Deadline for vendor to file (e.g. 7 days from notice)')),
                ('invoices_payload', models.JSONField(default=list, help_text='List of invoice details included in notice')),
                ('notice_text', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft Notice'), ('generated', 'Generated PDF'), ('sent_whatsapp', 'Sent via WhatsApp'), ('sent_email', 'Sent via Email'), ('resolved', 'Resolved / Vendor Filed'), ('disputed', 'Disputed')], default='generated', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_notices', to='billing.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GSTR2BRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('supplier_gstin', models.CharField(db_index=True, max_length=15)),
                ('supplier_trade_name', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_number', models.CharField(db_index=True, max_length=100)),
                ('normalized_invoice_number', models.CharField(db_index=True, max_length=100)),
                ('invoice_type', models.CharField(default='B2B', help_text='B2B, B2BA, CDNR, CDNRA, etc.', max_length=20)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('taxable_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('igst', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cess', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('itc_availability', models.CharField(default='Y', help_text="'Y' if eligible, 'N' if ineligible under Section 17(5)", max_length=10)),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('match_status', models.CharField(choices=[('matched', 'Matched with Purchase Bill'), ('probable', 'Probable Match'), ('missing_in_books', 'Present in 2B but Missing in Books'), ('tax_mismatch', 'Tax Amount Mismatch')], default='missing_in_books', max_length=30)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='billing.gstr2bimport')),
                ('matched_purchase_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gstr2b_records', to='billing.purchasebill')),
            ],
            options={
                'indexes': [models.Index(fields=['supplier_gstin', 'normalized_invoice_number'], name='billing_gst_supplie_0b0423_idx'), models.Index(fields=['created_by', 'match_status'], name='billing_gst_created_524323_idx')],
            },
        ),
    ]
