# Generated by Django 5.2.4 on 2026-10-03 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0037_purchasebill_gst_withheld_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverychallanitem',
            name='source_item_id',
            field=models.CharField(blank=True, help_text='ID of source SalesOrderItem', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='source_sales_order',
            field=models.ForeignKey(blank=True, help_text='Original sales order this purchase order was generated from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='billing.salesorder'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='source_item_id',
            field=models.CharField(blank=True, help_text='ID of source item in SalesOrder', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='source_item_id',
            field=models.CharField(blank=True, help_text='ID of upstream item if applicable', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='source_sales_order',
            field=models.ForeignKey(blank=True, help_text='Original sales order this invoice was converted from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoices', to='billing.salesorder'),
        ),
        migrations.AddField(
            model_name='salesinvoiceitem',
            name='source_item_id',
            field=models.CharField(blank=True, help_text='ID of source item in DeliveryChallan or SalesOrder', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='source_item_id',
            field=models.CharField(blank=True, help_text='ID of source QuotationItem', max_length=64, null=True),
        ),
    ]
