# Generated by Django 5.2.4 on 2026-10-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0038_deliverychallanitem_source_item_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='po_date',
            field=models.DateField(blank=True, help_text='Customer PO Date', null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='po_number',
            field=models.CharField(blank=True, help_text='Customer PO Number', max_length=100, null=True),
        ),
    ]
