# Generated by Django 5.2.4 on 2026-10-04 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0039_salesorder_po_date_salesorder_po_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesettings',
            name='show_item_manufacturer',
            field=models.BooleanField(default=True),
        ),
    ]
