version: "3.9"

services:
  web:
    build: .
    command: uvicorn cenvoras.asgi:application --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data/

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/ssl/certs/fullchain.crt:/etc/ssl/certs/fullchain.crt:ro
      - /etc/ssl/certs/privkey.key:/etc/ssl/certs/privkey.key:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro   # <-- mount your custom config
      - ./app/static:/app/static                                   # optional, if you serve static files
      - ./app/media:/app/media                                     # optional, if you serve media files
    depends_on:
      - web

volumes:
  pgdata:
