version: "3.9"

services:
  web:
    build: .
    command: ./entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    command: celery -A cenvoras worker -l info --pool=gevent --concurrency=100
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis
      - web

  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "8080:8080"
    environment:
      # DOZZLE_USERNAME and DOZZLE_PASSWORD restrict logs visually via UI
      - DOZZLE_USERNAME=admin
      - DOZZLE_PASSWORD=cenvoras_logs

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt/live/devapi.cenvora.app/fullchain.pem:/etc/nginx/cert.pem:ro
      - /etc/letsencrypt/live/devapi.cenvora.app/privkey.pem:/etc/nginx/privkey.pem:ro
      - ./staticfiles:/app/static:ro
      - ./media:/app/media:ro
    depends_on:
      - web

volumes:
  pgdata: