# Generated by Django 5.2.4 on 2025-10-01 16:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_customer_created_at'),
        ('ledger', '0003_account_journalentry_generalledgerentry_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='purchase_bill',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='sales_invoice',
        ),
        migrations.RemoveField(
            model_name='generalledgerentry',
            name='journal_entry',
        ),
        migrations.AlterModelOptions(
            name='generalledgerentry',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AddField(
            model_name='generalledgerentry',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalledgerentry',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalledgerentry',
            name='purchase_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.purchasebill'),
        ),
        migrations.AddField(
            model_name='generalledgerentry',
            name='reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='generalledgerentry',
            name='sales_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.salesinvoice'),
        ),
        migrations.AlterField(
            model_name='generalledgerentry',
            name='description',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='ClientLedgerEntry',
        ),
        migrations.DeleteModel(
            name='JournalEntry',
        ),
    ]
