# Generated by Django 5.2.4 on 2026-03-04 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_payment_invoice'),
        ('ledger', '0005_bankstatement_bankstatementline'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalledgerentry',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='billing.customer'),
        ),
    ]
