# Generated by Django 5.2.4 on 2026-04-27 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0024_quotation_entities'),
        ('ledger', '0006_generalledgerentry_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalledgerentry',
            name='credit_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.creditnote'),
        ),
        migrations.AddField(
            model_name='generalledgerentry',
            name='debit_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.debitnote'),
        ),
    ]
