# Generated by Django 5.2.4 on 2026-09-25 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_vendor_and_payment(apps, schema_editor):
    GeneralLedgerEntry = apps.get_model('ledger', 'GeneralLedgerEntry')
    Payment = apps.get_model('billing', 'Payment')
    
    # 1. Backfill vendor from purchase_bill
    entries_with_bill = GeneralLedgerEntry.objects.filter(
        purchase_bill__isnull=False,
        vendor__isnull=True
    ).select_related('purchase_bill')
    for entry in entries_with_bill:
        if entry.purchase_bill and getattr(entry.purchase_bill, 'vendor_id', None):
            entry.vendor_id = entry.purchase_bill.vendor_id
            entry.save(update_fields=['vendor'])

    # 2. Backfill vendor from debit_note
    entries_with_dn = GeneralLedgerEntry.objects.filter(
        debit_note__isnull=False,
        vendor__isnull=True
    ).select_related('debit_note')
    for entry in entries_with_dn:
        if entry.debit_note:
            v_id = getattr(entry.debit_note, 'vendor_id', None)
            if not v_id and getattr(entry.debit_note, 'original_bill_id', None):
                v_id = getattr(entry.debit_note.original_bill, 'vendor_id', None)
            if v_id:
                entry.vendor_id = v_id
                entry.save(update_fields=['vendor'])

    # 3. Backfill payment from reference pattern "Payment Received <uuid>"
    payment_entries = GeneralLedgerEntry.objects.filter(
        reference__startswith='Payment Received ',
        payment__isnull=True
    )
    for entry in payment_entries:
        try:
            raw_uuid = entry.reference.replace('Payment Received ', '').strip()
            if raw_uuid and Payment.objects.filter(id=raw_uuid).exists():
                entry.payment_id = raw_uuid
                entry.save(update_fields=['payment'])
        except Exception:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0032_salesorderitem_dispatched_quantity'),
        ('ledger', '0007_generalledgerentry_credit_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='generalledgerentry',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='billing.payment'),
        ),
        migrations.AddField(
            model_name='generalledgerentry',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='billing.vendor'),
        ),
        migrations.AddIndex(
            model_name='generalledgerentry',
            index=models.Index(fields=['created_by', 'date'], name='ledger_gene_created_f91ddd_idx'),
        ),
        migrations.AddIndex(
            model_name='generalledgerentry',
            index=models.Index(fields=['created_by', 'account', 'date'], name='ledger_gene_created_ad78dc_idx'),
        ),
        migrations.AddIndex(
            model_name='generalledgerentry',
            index=models.Index(fields=['created_by', 'customer', 'date'], name='ledger_gene_created_4067da_idx'),
        ),
        migrations.AddIndex(
            model_name='generalledgerentry',
            index=models.Index(fields=['created_by', 'vendor', 'date'], name='ledger_gene_created_6be2c8_idx'),
        ),
        migrations.RunPython(backfill_vendor_and_payment, reverse_code=migrations.RunPython.noop),
    ]

