# Generated by Django 5.2.4 on 2026-03-03 23:34

from django.db import migrations

def create_default_plans_and_migrate(apps, schema_editor):
    Plan = apps.get_model('subscription', 'Plan')
    TenantSubscription = apps.get_model('subscription', 'TenantSubscription')
    User = apps.get_model('users', 'User')
    
    # 1. Seed Default Plans
    starter, _ = Plan.objects.get_or_create(
        code='starter',
        defaults={
            'name': 'Starter Plan',
            'monthly_price': 0.00,
            'max_managers': 0,
            'max_invoices_per_month': 50
        }
    )
    
    growth, _ = Plan.objects.get_or_create(
        code='growth',
        defaults={
            'name': 'Growth Plan',
            'monthly_price': 999.00,
            'max_managers': 2,
            'max_invoices_per_month': -1
        }
    )
    
    enterprise, _ = Plan.objects.get_or_create(
        code='enterprise',
        defaults={
            'name': 'Enterprise Plan',
            'monthly_price': 2499.00,
            'max_managers': 5,
            'max_invoices_per_month': -1
        }
    )
    
    # 2. Migrate existing Users
    # Mapping legacy "subscription_tier" to the new "Plan" models
    tier_mapping = {
        'FREE': starter,
        'MID': growth,
        'PRO': enterprise
    }
    
    for user in User.objects.filter(parent__isnull=True): # Only create subs for Admins/Tenants
        # Safely determine the intended plan based on legacy tier or default to starter
        legacy_tier = getattr(user, 'subscription_tier', 'FREE')
        matched_plan = tier_mapping.get(legacy_tier, starter)
        
        # Safely determine the status
        legacy_status = getattr(user, 'subscription_status', 'trial')
        
        TenantSubscription.objects.get_or_create(
            tenant=user,
            defaults={
                'plan': matched_plan,
                'status': legacy_status
            }
        )

def reverse_migration(apps, schema_editor):
    TenantSubscription = apps.get_model('subscription', 'TenantSubscription')
    Plan = apps.get_model('subscription', 'Plan')
    
    TenantSubscription.objects.all().delete()
    Plan.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
        ('users', '0008_alter_user_phone'), # Ensure user model changes are processed first
    ]

    operations = [
        migrations.RunPython(create_default_plans_and_migrate, reverse_migration),
    ]

