# Generated by Django 5.2.4 on 2026-04-28 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0011_plan_quarterly_price_and_more'),
    ]

    def update_business_limits(apps, schema_editor):
        Plan = apps.get_model('subscription', 'Plan')
        Plan.objects.filter(code='business').update(max_managers=5, max_team_members=5)

    operations = [
        migrations.RunPython(update_business_limits),
    ]
