# Generated by Django 5.2.4 on 2026-05-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_log', '0002_auditlog_tenant_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('EMAIL', 'Email Sent'), ('BACKUP', 'Backup'), ('DOWNLOAD', 'Download')], max_length=10),
        ),
    ]
