# Generated by Django 5.2.4 on 2026-05-26 10:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalTaxSlab',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state_name', models.CharField(help_text='Indian state name (e.g. "Maharashtra").', max_length=100)),
                ('lower_bound', models.DecimalField(decimal_places=2, help_text='Minimum monthly gross salary (INR) for this slab to apply.', max_digits=10)),
                ('upper_bound', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum monthly gross salary (INR) for this slab; null = no upper limit.', max_digits=10, null=True)),
                ('pt_amount', models.DecimalField(decimal_places=2, help_text='Professional Tax amount (INR) to deduct for this slab.', max_digits=12)),
            ],
            options={
                'ordering': ['state_name', 'lower_bound'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_departments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_designations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_code', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('date_of_joining', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-Time'), ('part_time', 'Part-Time'), ('contract', 'Contract')], max_length=20)),
                ('work_state', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('personal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('personal_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True)),
                ('aadhaar_number', models.CharField(blank=True, max_length=12, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_ifsc', models.CharField(blank=True, max_length=11, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('uan', models.CharField(blank=True, max_length=12, null=True)),
                ('esi_ip_number', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='hr.department')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='hr.designation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_employees', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('tenant', 'employee_code')},
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('annual_entitlement', models.DecimalField(decimal_places=1, help_text='Number of days an employee is entitled to per calendar year.', max_digits=5)),
                ('is_paid', models.BooleanField(default=True, help_text='Whether days taken under this leave type are paid.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_leave_types', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('computed_days', models.DecimalField(decimal_places=1, default=0, help_text='Number of leave days computed from start/end date range.', max_digits=5)),
                ('lwp_days', models.DecimalField(decimal_places=1, default=0, help_text='Leave Without Pay days (excess beyond available balance).', max_digits=5)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to='hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_leave_applications', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='hr.leavetype')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.PositiveSmallIntegerField(help_text='Month of the payroll run (1 = January, 12 = December).')),
                ('year', models.PositiveIntegerField(help_text='Calendar year of the payroll run (e.g. 2025).')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('finalised', 'Finalised')], default='draft', max_length=15)),
                ('total_gross', models.DecimalField(decimal_places=2, default=0, help_text='Sum of gross salaries for all employees in this run.', max_digits=12)),
                ('total_net', models.DecimalField(decimal_places=2, default=0, help_text='Sum of net salaries for all employees in this run.', max_digits=12)),
                ('finalised_at', models.DateTimeField(blank=True, help_text='Timestamp when this payroll run was finalised.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_payroll_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('tenant', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_salary_structures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SalaryComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('component_type', models.CharField(choices=[('fixed', 'Fixed Amount'), ('pct_basic', 'Percentage of Basic'), ('pct_gross', 'Percentage of Gross')], max_length=15)),
                ('is_basic', models.BooleanField(default=False, help_text='Designates this component as the Basic salary component.')),
                ('value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('salary_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='hr.salarystructure')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSalaryAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effective_from', models.DateField()),
                ('monthly_ctc', models.DecimalField(decimal_places=2, help_text='Monthly Cost to Company (INR) used as the basis for percentage components.', max_digits=12)),
                ('computed_components', models.JSONField(default=dict, help_text='Snapshot of computed INR values per component at assignment time.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_assignments', to='hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_salary_assignments', to=settings.AUTH_USER_MODEL)),
                ('salary_structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='hr.salarystructure')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half_day', 'Half-Day'), ('leave', 'Leave'), ('holiday', 'Holiday')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_attendance', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='hr.employee')),
            ],
            options={
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField(help_text='Calendar year this balance applies to (e.g. 2025).')),
                ('balance', models.DecimalField(decimal_places=1, help_text='Remaining leave days available for this employee.', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='hr.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='hr.leavetype')),
            ],
            options={
                'unique_together': {('employee', 'leave_type', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('present_days', models.DecimalField(decimal_places=1, help_text='Effective present days (present=1.0, half_day=0.5, paid_leave=1.0).', max_digits=5)),
                ('total_working_days', models.PositiveSmallIntegerField(help_text='Total Mon–Sat working days in the payroll month.')),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('earnings', models.JSONField(default=dict, help_text='Breakdown of each earnings component (prorated INR amounts).')),
                ('deductions', models.JSONField(default=dict, help_text='Breakdown of each deduction (PF, ESI, TDS, PT).')),
                ('employee_pf', models.DecimalField(decimal_places=2, default=0, help_text='Employee PF contribution (12% of Basic).', max_digits=12)),
                ('employee_esi', models.DecimalField(decimal_places=2, default=0, help_text='Employee ESI contribution (0.75% of gross, if gross ≤ ₹21,000).', max_digits=12)),
                ('tds', models.DecimalField(decimal_places=2, default=0, help_text='Monthly TDS deducted (annualised slab / 12).', max_digits=12)),
                ('professional_tax', models.DecimalField(decimal_places=2, default=0, help_text='Professional Tax deducted per state slab.', max_digits=12)),
                ('employer_pf', models.DecimalField(decimal_places=2, default=0, help_text='Total employer PF contribution (12% of Basic).', max_digits=12)),
                ('employer_epf', models.DecimalField(decimal_places=2, default=0, help_text='Employer EPF portion (3.67% of Basic).', max_digits=12)),
                ('employer_eps', models.DecimalField(decimal_places=2, default=0, help_text='Employer EPS portion (8.33% of Basic).', max_digits=12)),
                ('employer_esi', models.DecimalField(decimal_places=2, default=0, help_text='Employer ESI contribution (3.25% of gross, if gross ≤ ₹21,000).', max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, help_text='Net take-home salary after all deductions.', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='hr.employee')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='hr.payrollrun')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_payslips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['employee__employee_code'],
                'unique_together': {('payroll_run', 'employee')},
            },
        ),
    ]
