# Generated by Django 5.2.4 on 2026-05-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salarycomponent',
            options={'ordering': ['salary_structure', 'order', 'name']},
        ),
        migrations.AddField(
            model_name='salarycomponent',
            name='order',
            field=models.IntegerField(default=0, help_text='Display ordering of this component within the salary structure.'),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of this salary structure.'),
        ),
    ]
