# Generated by Django 5.2.4 on 2026-05-31 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_employeequery_employeetask'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetask',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
