# Generated by Django 5.2.4 on 2026-09-05 12:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_employeenotification'),
        ('inventory', '0018_productmeta_storage_condition_and_more'),
        ('ledger', '0007_generalledgerentry_credit_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='father_mother_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='employee_photos/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_photo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='reporting_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='carry_forward_max_days',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Maximum unused days allowed to carry forward to the next year.', max_digits=5),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='max_consecutive_days',
            field=models.PositiveSmallIntegerField(default=0, help_text='Maximum consecutive days allowed in a single application (0 = unlimited).'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='requires_approval',
            field=models.BooleanField(default=True, help_text='Whether leave applications under this type require managerial approval.'),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payroll_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='is_reopened',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_payroll_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_payroll_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='payment_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_payments', to='ledger.account'),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='reopen_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='reopened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='reopened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reopened_payroll_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sum of employee deductions for all employees in this run.', max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='total_employer_contributions',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sum of employer contributions (PF, ESI) for this run.', max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='absent_days',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='payslip',
            name='advance_recovery',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='employer_total_contribution',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='loan_recovery',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='lop_days',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='payslip',
            name='overtime_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='payslip',
            name='paid_leave_days',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='payslip',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salarycomponent',
            name='calculation_base',
            field=models.CharField(blank=True, default='basic', max_length=50),
        ),
        migrations.AddField(
            model_name='salarycomponent',
            name='employee_contribution_pct',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='salarycomponent',
            name='employer_contribution_pct',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='salarycomponent',
            name='esi_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salarycomponent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='salarycomponent',
            name='is_taxable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='salarycomponent',
            name='percentage',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='salarycomponent',
            name='pf_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salarycomponent',
            name='pt_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salarycomponent',
            name='tds_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salarycomponent',
            name='type',
            field=models.CharField(choices=[('earning', 'Earning'), ('deduction', 'Deduction')], default='earning', max_length=15),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('resigned', 'Resigned'), ('terminated', 'Terminated'), ('inactive', 'Inactive')], default='active', max_length=15),
        ),
        migrations.AlterField(
            model_name='payrollrun',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('calculating', 'Calculating'), ('calculated', 'Calculated'), ('completed', 'Completed'), ('processing', 'Processing'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('paid', 'Paid'), ('locked', 'Locked'), ('finalised', 'Finalised'), ('failed', 'Failed')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='deductions',
            field=models.JSONField(default=dict, help_text='Breakdown of each deduction.'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='employee_esi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='employee_pf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='employer_epf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='employer_eps',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='employer_esi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='employer_pf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='professional_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='tds',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='total_working_days',
            field=models.PositiveSmallIntegerField(help_text='Total working days in the payroll month.'),
        ),
        migrations.AlterField(
            model_name='salarycomponent',
            name='component_type',
            field=models.CharField(choices=[('fixed', 'Fixed Amount'), ('pct_basic', 'Percentage of Basic'), ('pct_gross', 'Percentage of Gross'), ('pct_ctc', 'Percentage of CTC')], default='fixed', max_length=15),
        ),
        migrations.AlterField(
            model_name='salarycomponent',
            name='value',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='EmployeeAdvanceLoan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_type', models.CharField(choices=[('advance', 'Salary Advance'), ('loan', 'Employee Loan')], default='advance', max_length=10)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monthly_installment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('disbursement_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('fully_recovered', 'Fully Recovered'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disbursed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursed_advances_loans', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances_loans', to='hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_advances_loans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-disbursement_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalaryHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effective_date', models.DateField()),
                ('previous_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('new_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_salary_revisions', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_history', to='hr.employee')),
                ('salary_structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_histories', to='hr.salarystructure')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_salary_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HRDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('offer_letter', 'Offer Letter'), ('appointment_letter', 'Appointment Letter'), ('id_proof', 'ID Proof'), ('tax_form', 'Tax Declaration Form'), ('resignation', 'Resignation Letter'), ('appraisal', 'Appraisal Letter'), ('other', 'Other Document')], default='other', max_length=30)),
                ('file', models.FileField(blank=True, null=True, upload_to='hr_documents/')),
                ('file_url', models.URLField(blank=True, max_length=500, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_documents', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HRMSSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payroll_frequency', models.CharField(default='monthly', max_length=20)),
                ('payroll_cutoff_day', models.PositiveSmallIntegerField(default=25)),
                ('default_working_days', models.PositiveSmallIntegerField(default=26)),
                ('lop_calculation_rule', models.CharField(choices=[('working_days', 'Working Days (Excluding Weekends)'), ('calendar_days', 'Calendar Days in Month'), ('fixed_30', 'Fixed 30 Days Basis')], default='working_days', max_length=30)),
                ('overtime_multiplier', models.DecimalField(decimal_places=2, default=1.5, max_digits=4)),
                ('allow_negative_salary', models.BooleanField(default=False)),
                ('salary_rounding', models.CharField(choices=[('nearest_one', 'Nearest ₹1'), ('nearest_ten', 'Nearest ₹10'), ('exact', 'Exact 2 Decimals')], default='nearest_one', max_length=20)),
                ('pf_employee_rate', models.DecimalField(decimal_places=2, default=12.0, max_digits=5)),
                ('pf_employer_rate', models.DecimalField(decimal_places=2, default=12.0, max_digits=5)),
                ('pf_wage_ceiling', models.DecimalField(decimal_places=2, default=15000.0, max_digits=10)),
                ('pf_apply_ceiling', models.BooleanField(default=False)),
                ('esi_employee_rate', models.DecimalField(decimal_places=3, default=0.75, max_digits=5)),
                ('esi_employer_rate', models.DecimalField(decimal_places=3, default=3.25, max_digits=5)),
                ('esi_wage_ceiling', models.DecimalField(decimal_places=2, default=21000.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hrms_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoanRecoveryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recovery_date', models.DateField()),
                ('amount_recovered', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoveries', to='hr.employeeadvanceloan')),
                ('payslip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_recoveries', to='hr.payslip')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_recovery_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recovery_date'],
            },
        ),
        migrations.CreateModel(
            name='OvertimeRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('multiplier', models.DecimalField(decimal_places=2, default=1.5, max_digits=4)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_overtimes', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_records', to='hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_overtime_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning')], default='warning', max_length=10)),
                ('code', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payroll_exceptions', to='hr.employee')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='hr.payrollrun')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_payroll_exceptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['severity', 'created_at'],
            },
        ),
    ]
