# Generated by Django 5.2.4 on 2026-09-22 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_employee_account_holder_name_employee_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='hr.employee'),
        ),
    ]
