# Generated by Django 5.2.4 on 2026-09-22 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_employeeallowancebonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='deduction_reasons',
            field=models.JSONField(blank=True, default=dict, help_text='Itemized breakdown explaining the reason and calculation for each deduction.'),
        ),
        migrations.AlterField(
            model_name='employeeadvanceloan',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('active', 'Active'), ('fully_recovered', 'Fully Recovered'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
    ]
