# Generated by Django 5.2.4 on 2026-09-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_payslip_deduction_reasons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrun',
            name='reopen_history',
            field=models.JSONField(blank=True, default=list, help_text='Audit log of all reopen events with user, timestamp, and reason.'),
        ),
    ]
