# Generated by Django 5.2.4 on 2026-09-23 13:33

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_payrollrun_reopen_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='tax_regime',
            field=models.CharField(choices=[('new', 'New Regime'), ('old', 'Old Regime')], default='new', help_text='Employee Indian Income Tax regime preference under Section 115BAC (defaults to New Regime).', max_length=10),
        ),
        migrations.CreateModel(
            name='EmployeeTaxDeclaration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('financial_year', models.CharField(help_text='Financial year in format YYYY-YYYY, e.g. 2026-2027', max_length=10)),
                ('regime', models.CharField(choices=[('new', 'New Regime'), ('old', 'Old Regime')], default='new', max_length=10)),
                ('section_80c', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Section 80C deductions (PPF, ELSS, EPF, Life Insurance, etc. - max 1,50,000)', max_digits=10)),
                ('section_80d', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Section 80D medical health insurance premium', max_digits=10)),
                ('section_24b_home_loan', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Section 24(b) interest on self-occupied housing loan (max 2,00,000)', max_digits=10)),
                ('hra_exemption', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Declared annual House Rent Allowance exemption under Section 10(13A)', max_digits=10)),
                ('other_exemptions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Other eligible chapter VI-A exemptions (80E, 80G, 80TTA)', max_digits=10)),
                ('declared_previous_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Gross income earned from previous employer during current FY (Form 12B)', max_digits=12)),
                ('declared_previous_tds', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='TDS deducted by previous employer during current FY (Form 12B)', max_digits=12)),
                ('proof_submitted', models.BooleanField(default=False, help_text='Whether employee has uploaded formal supporting investment proofs for declarations.')),
                ('proof_verified', models.BooleanField(default=False, help_text='Whether HR has verified and approved supporting investment proofs.')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_declarations', to='hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_tax_declarations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-financial_year', 'employee__full_name'],
                'unique_together': {('tenant', 'employee', 'financial_year')},
            },
        ),
    ]
