# Generated by Django 5.2.4 on 2026-09-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_employee_tax_regime_employeetaxdeclaration'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrmssettings',
            name='weekend_rule',
            field=models.CharField(choices=[('sunday_only', 'Sunday Only (6-Day Work Week)'), ('sat_sun', 'Saturday & Sunday (5-Day Work Week)')], default='sunday_only', max_length=30),
        ),
        migrations.AlterField(
            model_name='hrmssettings',
            name='lop_calculation_rule',
            field=models.CharField(choices=[('working_days', 'Working Days (Excluding Weekends)'), ('working_days_5', '5-Day Week (Excluding Saturdays & Sundays)'), ('calendar_days', 'Calendar Days in Month'), ('fixed_30', 'Fixed 30 Days Basis')], default='working_days', max_length=30),
        ),
    ]
