"""
Unit tests for hr/services/audit_service.py

Validates Requirements: 13.1, 13.2, 13.3, 13.4

Tests verify that AuditLog records are created with correct fields for each
action type: log_create, log_update, log_delete, log_download.
"""

import datetime
from unittest.mock import MagicMock

from django.test import TestCase

from audit_log.models import AuditLog
from hr.models import Department, Designation, Employee
from hr.services import audit_service
from users.models import User


def make_request(user, ip='192.168.1.1', forwarded_for=None):
    """
    Build a minimal mock request object that audit_service functions expect.

    Args:
        user: The User instance acting as the requester.
        ip: REMOTE_ADDR value.
        forwarded_for: Optional X-Forwarded-For header value.
    """
    request = MagicMock()
    request.user = user
    request.META = {'REMOTE_ADDR': ip}
    if forwarded_for:
        request.META['HTTP_X_FORWARDED_FOR'] = forwarded_for
    return request


class AuditServiceSetupMixin:
    """
    Shared setUp logic: creates a tenant user and a minimal Employee instance
    so tests have real model objects to pass to the audit helpers.
    """

    def setUp(self):
        # Tenant (root user — parent is None)
        self.tenant = User.objects.create_user(
            username='tenant_owner',
            email='owner@example.com',
            password='testpass123',
            business_name='Test Corp',
        )
        # Sub-user (team member) whose active_tenant resolves to self.tenant
        self.user = User.objects.create_user(
            username='hr_admin',
            email='hradmin@example.com',
            password='testpass123',
            parent=self.tenant,
            role='admin',
        )

        # Minimal department and designation required by Employee
        self.dept = Department.objects.create(tenant=self.tenant, name='Engineering')
        self.desig = Designation.objects.create(tenant=self.tenant, name='Engineer')

        # A real Employee instance to use as the audited object
        self.employee = Employee.objects.create(
            tenant=self.tenant,
            full_name='Jane Doe',
            date_of_birth=datetime.date(1990, 1, 15),
            date_of_joining=datetime.date(2022, 6, 1),
            gender='F',
            employment_type='full_time',
            department=self.dept,
            designation=self.desig,
            work_state='Maharashtra',
        )

        # Clear any AuditLogs generated by model creation signals or previous tests
        AuditLog.objects.all().delete()


class LogCreateTests(AuditServiceSetupMixin, TestCase):
    """Tests for audit_service.log_create — Requirement 13.1, 13.3, 13.4"""

    def test_creates_audit_log_record(self):
        """log_create must persist exactly one AuditLog row."""
        request = make_request(self.user)
        audit_service.log_create(request, self.employee)
        self.assertEqual(AuditLog.objects.count(), 1)

    def test_action_is_create(self):
        """AuditLog.action must be 'CREATE'."""
        request = make_request(self.user)
        audit_service.log_create(request, self.employee)
        log = AuditLog.objects.get()
        self.assertEqual(log.action, 'CREATE')

    def test_model_name_defaults_to_class_name(self):
        """model_name defaults to the instance's class name."""
        request = make_request(self.user)
        audit_service.log_create(request, self.employee)
        log = AuditLog.objects.get()
        self.assertEqual(log.model_name, 'Employee')

    def test_model_name_override(self):
        """model_name can be overridden via the model_name kwarg."""
        request = make_request(self.user)
        audit_service.log_create(request, self.employee, model_name='CustomModel')
        log = AuditLog.objects.get()
        self.assertEqual(log.model_name, 'CustomModel')

    def test_object_id_matches_instance_pk(self):
        """object_id must be the string representation of the instance PK."""
        request = make_request(self.user)
        audit_service.log_create(request, self.employee)
        log = AuditLog.objects.get()
        self.assertEqual(log.object_id, str(self.employee.pk))

    def test_object_repr_is_populated(self):
        """object_repr must be a non-empty string representation of the instance."""
        request = make_request(self.user)
        audit_service.log_create(request, self.employee)
        log = AuditLog.objects.get()
        self.assertTrue(log.object_repr)
        self.assertIn(self.employee.employee_code, log.object_repr)

    def test_tenant_is_active_tenant(self):
        """tenant FK must be set to request.user.active_tenant (Requirement 13.3)."""
        request = make_request(self.user)
        audit_service.log_create(request, self.employee)
        log = AuditLog.objects.get()
        self.assertEqual(log.tenant, self.tenant)

    def test_user_is_set(self):
        """user FK must be the requesting user."""
        request = make_request(self.user)
        audit_service.log_create(request, self.employee)
        log = AuditLog.objects.get()
        self.assertEqual(log.user, self.user)

    def test_user_email_snapshot(self):
        """user_email must capture the email at log time."""
        request = make_request(self.user)
        audit_service.log_create(request, self.employee)
        log = AuditLog.objects.get()
        self.assertEqual(log.user_email, self.user.email)

    def test_ip_address_from_remote_addr(self):
        """ip_address must be populated from REMOTE_ADDR (Requirement 13.4)."""
        request = make_request(self.user, ip='10.0.0.5')
        audit_service.log_create(request, self.employee)
        log = AuditLog.objects.get()
        self.assertEqual(log.ip_address, '10.0.0.5')

    def test_ip_address_prefers_x_forwarded_for(self):
        """ip_address must use the first IP in X-Forwarded-For when present."""
        request = make_request(self.user, ip='10.0.0.1', forwarded_for='203.0.113.5, 10.0.0.1')
        audit_service.log_create(request, self.employee)
        log = AuditLog.objects.get()
        self.assertEqual(log.ip_address, '203.0.113.5')

    def test_changes_defaults_to_empty_dict(self):
        """changes must default to an empty dict when not supplied."""
        request = make_request(self.user)
        audit_service.log_create(request, self.employee)
        log = AuditLog.objects.get()
        self.assertEqual(log.changes, {})

    def test_changes_can_be_supplied(self):
        """changes can be passed explicitly and must be stored as-is."""
        request = make_request(self.user)
        initial_data = {'full_name': 'Jane Doe', 'status': 'active'}
        audit_service.log_create(request, self.employee, changes=initial_data)
        log = AuditLog.objects.get()
        self.assertEqual(log.changes, initial_data)

    def test_tenant_user_as_requester(self):
        """log_create works when the requester is the tenant itself (parent=None)."""
        request = make_request(self.tenant)
        audit_service.log_create(request, self.employee)
        log = AuditLog.objects.get()
        # active_tenant for a root user is self
        self.assertEqual(log.tenant, self.tenant)
        self.assertEqual(log.user, self.tenant)


class LogUpdateTests(AuditServiceSetupMixin, TestCase):
    """Tests for audit_service.log_update — Requirements 13.1, 13.2, 13.3, 13.4"""

    def test_creates_audit_log_record(self):
        """log_update must persist exactly one AuditLog row."""
        request = make_request(self.user)
        audit_service.log_update(request, self.employee, before={'status': 'active'}, after={'status': 'inactive'})
        self.assertEqual(AuditLog.objects.count(), 1)

    def test_action_is_update(self):
        """AuditLog.action must be 'UPDATE'."""
        request = make_request(self.user)
        audit_service.log_update(request, self.employee, before={}, after={})
        log = AuditLog.objects.get()
        self.assertEqual(log.action, 'UPDATE')

    def test_changes_contains_before_and_after(self):
        """changes must store both 'before' and 'after' keys (Requirement 13.2)."""
        before = {'full_name': 'Jane Doe', 'status': 'active'}
        after = {'full_name': 'Jane Smith', 'status': 'active'}
        request = make_request(self.user)
        audit_service.log_update(request, self.employee, before=before, after=after)
        log = AuditLog.objects.get()
        self.assertIn('before', log.changes)
        self.assertIn('after', log.changes)
        self.assertEqual(log.changes['before'], before)
        self.assertEqual(log.changes['after'], after)

    def test_model_name_defaults_to_class_name(self):
        """model_name defaults to the instance's class name."""
        request = make_request(self.user)
        audit_service.log_update(request, self.employee, before={}, after={})
        log = AuditLog.objects.get()
        self.assertEqual(log.model_name, 'Employee')

    def test_model_name_override(self):
        """model_name can be overridden."""
        request = make_request(self.user)
        audit_service.log_update(request, self.employee, before={}, after={}, model_name='Payslip')
        log = AuditLog.objects.get()
        self.assertEqual(log.model_name, 'Payslip')

    def test_object_id_matches_instance_pk(self):
        """object_id must be the string PK of the updated instance."""
        request = make_request(self.user)
        audit_service.log_update(request, self.employee, before={}, after={})
        log = AuditLog.objects.get()
        self.assertEqual(log.object_id, str(self.employee.pk))

    def test_tenant_is_active_tenant(self):
        """tenant FK must be the active tenant (Requirement 13.3)."""
        request = make_request(self.user)
        audit_service.log_update(request, self.employee, before={}, after={})
        log = AuditLog.objects.get()
        self.assertEqual(log.tenant, self.tenant)

    def test_ip_address_populated(self):
        """ip_address must be populated from the request (Requirement 13.4)."""
        request = make_request(self.user, ip='172.16.0.1')
        audit_service.log_update(request, self.employee, before={}, after={})
        log = AuditLog.objects.get()
        self.assertEqual(log.ip_address, '172.16.0.1')

    def test_empty_before_and_after_stored(self):
        """Empty before/after dicts are stored without error."""
        request = make_request(self.user)
        audit_service.log_update(request, self.employee, before={}, after={})
        log = AuditLog.objects.get()
        self.assertEqual(log.changes, {'before': {}, 'after': {}})

    def test_nested_changes_preserved(self):
        """Nested dict values in before/after are preserved exactly."""
        before = {'address': {'city': 'Mumbai', 'state': 'Maharashtra'}}
        after = {'address': {'city': 'Pune', 'state': 'Maharashtra'}}
        request = make_request(self.user)
        audit_service.log_update(request, self.employee, before=before, after=after)
        log = AuditLog.objects.get()
        self.assertEqual(log.changes['before'], before)
        self.assertEqual(log.changes['after'], after)


class LogDeleteTests(AuditServiceSetupMixin, TestCase):
    """Tests for audit_service.log_delete — Requirements 13.1, 13.3, 13.4"""

    def test_creates_audit_log_record(self):
        """log_delete must persist exactly one AuditLog row."""
        request = make_request(self.user)
        audit_service.log_delete(request, self.employee)
        self.assertEqual(AuditLog.objects.count(), 1)

    def test_action_is_delete(self):
        """AuditLog.action must be 'DELETE'."""
        request = make_request(self.user)
        audit_service.log_delete(request, self.employee)
        log = AuditLog.objects.get()
        self.assertEqual(log.action, 'DELETE')

    def test_model_name_defaults_to_class_name(self):
        """model_name defaults to the instance's class name."""
        request = make_request(self.user)
        audit_service.log_delete(request, self.employee)
        log = AuditLog.objects.get()
        self.assertEqual(log.model_name, 'Employee')

    def test_model_name_override(self):
        """model_name can be overridden."""
        request = make_request(self.user)
        audit_service.log_delete(request, self.employee, model_name='Department')
        log = AuditLog.objects.get()
        self.assertEqual(log.model_name, 'Department')

    def test_object_id_matches_instance_pk(self):
        """object_id must be the string PK of the deleted instance."""
        request = make_request(self.user)
        audit_service.log_delete(request, self.employee)
        log = AuditLog.objects.get()
        self.assertEqual(log.object_id, str(self.employee.pk))

    def test_object_repr_is_populated(self):
        """object_repr must be a non-empty string."""
        request = make_request(self.user)
        audit_service.log_delete(request, self.employee)
        log = AuditLog.objects.get()
        self.assertTrue(log.object_repr)

    def test_changes_is_empty_dict(self):
        """changes must be an empty dict for DELETE entries."""
        request = make_request(self.user)
        audit_service.log_delete(request, self.employee)
        log = AuditLog.objects.get()
        self.assertEqual(log.changes, {})

    def test_tenant_is_active_tenant(self):
        """tenant FK must be the active tenant (Requirement 13.3)."""
        request = make_request(self.user)
        audit_service.log_delete(request, self.employee)
        log = AuditLog.objects.get()
        self.assertEqual(log.tenant, self.tenant)

    def test_ip_address_populated(self):
        """ip_address must be populated from the request (Requirement 13.4)."""
        request = make_request(self.user, ip='192.168.0.99')
        audit_service.log_delete(request, self.employee)
        log = AuditLog.objects.get()
        self.assertEqual(log.ip_address, '192.168.0.99')

    def test_log_created_before_actual_delete(self):
        """
        Audit log can be created for an instance that is subsequently deleted
        from the database — the log retains the object_id and object_repr.
        """
        request = make_request(self.user)
        employee_pk = str(self.employee.pk)
        employee_repr = str(self.employee)
        audit_service.log_delete(request, self.employee)
        # Now actually delete the employee
        self.employee.delete()
        log = AuditLog.objects.filter(object_id=employee_pk).order_by('-id').first()
        self.assertEqual(log.object_id, employee_pk)
        self.assertEqual(log.object_repr, employee_repr[:255])


class LogDownloadTests(AuditServiceSetupMixin, TestCase):
    """Tests for audit_service.log_download — Requirements 13.1, 13.3, 13.4"""

    def test_creates_audit_log_record(self):
        """log_download must persist exactly one AuditLog row."""
        request = make_request(self.user)
        audit_service.log_download(request, self.employee)
        self.assertEqual(AuditLog.objects.count(), 1)

    def test_action_is_download(self):
        """AuditLog.action must be 'DOWNLOAD'."""
        request = make_request(self.user)
        audit_service.log_download(request, self.employee)
        log = AuditLog.objects.get()
        self.assertEqual(log.action, 'DOWNLOAD')

    def test_download_action_is_valid_choice(self):
        """'DOWNLOAD' must be a valid choice in AuditLog.ACTION_CHOICES."""
        valid_actions = [choice[0] for choice in AuditLog.ACTION_CHOICES]
        self.assertIn('DOWNLOAD', valid_actions)

    def test_model_name_defaults_to_class_name(self):
        """model_name defaults to the instance's class name."""
        request = make_request(self.user)
        audit_service.log_download(request, self.employee)
        log = AuditLog.objects.get()
        self.assertEqual(log.model_name, 'Employee')

    def test_model_name_override_payslip(self):
        """model_name can be overridden to 'Payslip' as required by Requirement 10.4."""
        request = make_request(self.user)
        audit_service.log_download(request, self.employee, model_name='Payslip')
        log = AuditLog.objects.get()
        self.assertEqual(log.model_name, 'Payslip')

    def test_object_id_matches_instance_pk(self):
        """object_id must be the string PK of the downloaded instance."""
        request = make_request(self.user)
        audit_service.log_download(request, self.employee)
        log = AuditLog.objects.get()
        self.assertEqual(log.object_id, str(self.employee.pk))

    def test_changes_is_empty_dict(self):
        """changes must be an empty dict for DOWNLOAD entries."""
        request = make_request(self.user)
        audit_service.log_download(request, self.employee)
        log = AuditLog.objects.get()
        self.assertEqual(log.changes, {})

    def test_tenant_is_active_tenant(self):
        """tenant FK must be the active tenant (Requirement 13.3)."""
        request = make_request(self.user)
        audit_service.log_download(request, self.employee)
        log = AuditLog.objects.get()
        self.assertEqual(log.tenant, self.tenant)

    def test_ip_address_populated(self):
        """ip_address must be populated from the request (Requirement 13.4)."""
        request = make_request(self.user, ip='10.10.10.10')
        audit_service.log_download(request, self.employee)
        log = AuditLog.objects.get()
        self.assertEqual(log.ip_address, '10.10.10.10')

    def test_ip_address_prefers_x_forwarded_for(self):
        """ip_address uses the first IP in X-Forwarded-For when present."""
        request = make_request(self.user, ip='10.0.0.1', forwarded_for='198.51.100.7, 10.0.0.1')
        audit_service.log_download(request, self.employee)
        log = AuditLog.objects.get()
        self.assertEqual(log.ip_address, '198.51.100.7')

    def test_user_email_snapshot(self):
        """user_email must capture the email at log time."""
        request = make_request(self.user)
        audit_service.log_download(request, self.employee)
        log = AuditLog.objects.get()
        self.assertEqual(log.user_email, self.user.email)


class MultipleLogsTests(AuditServiceSetupMixin, TestCase):
    """Tests verifying that multiple audit log entries can coexist correctly."""

    def test_multiple_actions_create_separate_records(self):
        """Each audit helper call creates a distinct AuditLog row."""
        request = make_request(self.user)
        audit_service.log_create(request, self.employee)
        audit_service.log_update(request, self.employee, before={'status': 'active'}, after={'status': 'inactive'})
        audit_service.log_delete(request, self.employee)
        audit_service.log_download(request, self.employee)
        self.assertEqual(AuditLog.objects.count(), 4)

    def test_action_types_are_distinct(self):
        """All four action types are recorded correctly in a single test run."""
        request = make_request(self.user)
        audit_service.log_create(request, self.employee)
        audit_service.log_update(request, self.employee, before={}, after={})
        audit_service.log_delete(request, self.employee)
        audit_service.log_download(request, self.employee)
        actions = set(AuditLog.objects.values_list('action', flat=True))
        self.assertEqual(actions, {'CREATE', 'UPDATE', 'DELETE', 'DOWNLOAD'})

    def test_different_model_names_stored_correctly(self):
        """model_name overrides are stored independently per log entry."""
        request = make_request(self.user)
        dept = Department.objects.create(tenant=self.tenant, name='Finance')
        audit_service.log_create(request, self.employee, model_name='Employee')
        audit_service.log_create(request, dept, model_name='Department')
        model_names = set(AuditLog.objects.values_list('model_name', flat=True))
        self.assertIn('Employee', model_names)
        self.assertIn('Department', model_names)
