# Generated by Django 5.2.4 on 2025-08-05 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='hsn_code',
            new_name='hsn_sac_code',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='purchase_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='tax_rate',
            new_name='tax',
        ),
    ]
