# Generated by Django 5.2.4 on 2025-12-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_stockpoint_unique_together_stocktransfer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='conversion_factor',
            field=models.PositiveIntegerField(default=1, help_text='1 Secondary Unit = X Primary Units'),
        ),
        migrations.AddField(
            model_name='product',
            name='secondary_unit',
            field=models.CharField(blank=True, help_text='e.g., Box', max_length=20, null=True),
        ),
    ]
