# Generated by Django 5.2.4 on 2026-02-10 20:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_product_conversion_factor_product_secondary_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="BOM Name e.g. 'Standard Pack'", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('components', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('finished_good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductBatchMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfg_date', models.DateField(blank=True, null=True)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta', to='inventory.productbatch')),
            ],
        ),
        migrations.CreateModel(
            name='ProductMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secondary_stock', models.DecimalField(decimal_places=2, default=0, help_text='Stock held at distributor/secondary location', max_digits=10)),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of tags/substitutes for search')),
                ('is_h1', models.BooleanField(default=False, help_text='Schedule H1 Drug')),
                ('is_narcotic', models.BooleanField(default=False, help_text='Narcotic Drug')),
                ('bag_weight', models.DecimalField(decimal_places=3, default=0, help_text='Weight per bag', max_digits=10)),
                ('tare_weight', models.DecimalField(decimal_places=3, default=0, help_text='Empty bag weight', max_digits=10)),
                ('mandi_tax', models.DecimalField(decimal_places=2, default=0, help_text='Mandi Tax %', max_digits=5)),
                ('labour_charge', models.DecimalField(decimal_places=2, default=0, help_text='Labour charge per unit/bag', max_digits=10)),
                ('is_new_launch', models.BooleanField(default=False, help_text='Highlight in UI as New Launch')),
                ('salt_composition', models.TextField(blank=True, help_text='Chemical composition for pharmacy search', null=True)),
                ('bundle_items', models.JSONField(blank=True, default=list, help_text='Items to auto-add when this product is billed')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta', to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='StockJournal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('voucher_no', models.CharField(blank=True, max_length=50)),
                ('adjustment_type', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='StockJournalItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(help_text='Positive for Add, Negative for Deduct')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.productbatch')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockjournal')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
            ],
        ),
    ]
