# Generated by Django 5.2.4 on 2026-02-14 18:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_billofmaterial_productbatchmeta_productmeta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. Wholesale 2024', max_length=100)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('party_category', models.CharField(blank=True, choices=[('retailer', 'Retailer'), ('wholesaler', 'Wholesaler'), ('distributor', 'Distributor'), ('consumer', 'End Consumer')], help_text='Applies to all customers in this category', max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. Diwali Bonanza', max_length=100)),
                ('scheme_type', models.CharField(choices=[('bogo', 'Buy X Get Y (Free)'), ('flat_discount', 'Flat Discount Amount'), ('percentage_discount', 'Percentage Discount')], max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('min_qty', models.PositiveIntegerField(default=1, help_text='Min Qty to trigger scheme')),
                ('free_qty', models.PositiveIntegerField(default=0, help_text='Get Y Free')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('free_product', models.ForeignKey(blank=True, help_text='For BOGO', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schemes_as_free', to='inventory.product')),
                ('product', models.ForeignKey(help_text='Product on which scheme is applied', on_delete=django.db.models.deletion.CASCADE, related_name='schemes_active', to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='PriceListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Override Price', max_digits=10)),
                ('min_qty', models.PositiveIntegerField(default=1, help_text='Min Qty for this price')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.pricelist')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
            options={
                'unique_together': {('price_list', 'product', 'min_qty')},
            },
        ),
    ]
