# Generated by Django 5.2.4 on 2026-02-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_pricelist_scheme_pricelistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmeta',
            name='barcode',
            field=models.CharField(blank=True, help_text='EAN/UPC barcode for scanning', max_length=100, null=True, unique=True),
        ),
    ]
