# Generated by Django 5.2.4 on 2026-02-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_productmeta_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmeta',
            name='crate_qty',
            field=models.PositiveIntegerField(default=0, help_text='Number of crates/containers issued'),
        ),
        migrations.AddField(
            model_name='productmeta',
            name='crate_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Deposit rate per crate', max_digits=10),
        ),
        migrations.AddField(
            model_name='productmeta',
            name='is_returnable_packaging',
            field=models.BooleanField(default=False, help_text='Product uses returnable crates/containers'),
        ),
    ]
