# Generated by Django 5.2.4 on 2026-03-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_productmeta_crate_qty_productmeta_crate_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofmaterial',
            name='batch_size',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='production_time',
            field=models.CharField(blank=True, help_text='e.g., 2 Hours, 1 Day', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='testing_notes',
            field=models.TextField(blank=True, help_text='Quality testing notes for the finished good', null=True),
        ),
        migrations.AddField(
            model_name='productbatch',
            name='notes',
            field=models.TextField(blank=True, help_text='Custom remarks for this batch', null=True),
        ),
    ]
