# Generated by Django 5.2.4 on 2026-03-04 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_billofmaterial_batch_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofmaterial',
            name='finished_good_name',
            field=models.CharField(blank=True, help_text='Plain text name if no product is linked', max_length=255),
        ),
        migrations.AlterField(
            model_name='billofmaterial',
            name='finished_good',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boms', to='inventory.product'),
        ),
    ]
