# Generated by Django 5.2.4 on 2026-03-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_billofmaterial_finished_good_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmeta',
            name='bag_weight',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, help_text='Weight per bag', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productmeta',
            name='labour_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Labour charge per unit/bag', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productmeta',
            name='mandi_tax',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Mandi Tax %', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='productmeta',
            name='secondary_stock',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Stock held at distributor/secondary location', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productmeta',
            name='tare_weight',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, help_text='Empty bag weight', max_digits=10, null=True),
        ),
    ]
