# Generated by Django 5.2.4 on 2026-03-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_productmeta_bag_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmeta',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Default expiry date for the product', null=True),
        ),
    ]
