# Generated by Django 5.2.4 on 2026-03-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_productmeta_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='warranty_months',
            field=models.PositiveIntegerField(default=0, help_text='Warranty duration in months (0 = no warranty)'),
        ),
    ]
