# Generated by Django 5.2.4 on 2026-04-30 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_product_unit_choices_and_optional_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, help_text='Global stock count (Cached, may be negative if sales exceed purchases)'),
        ),
    ]
