# Generated by Django 5.2.4 on 2026-04-30 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmeta',
            name='storage_condition',
            field=models.CharField(blank=True, help_text="Specific storage conditions (e.g., 'Store in a cool, dry place')", max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='productmeta',
            name='temperature',
            field=models.CharField(blank=True, help_text="Required storage temperature (e.g., '2-8 °C')", max_length=50, null=True),
        ),
    ]
