# Generated by Django 5.2.4 on 2026-09-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_product_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='cost_price',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Purchase cost for this batch', max_digits=14),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='mrp',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Maximum Retail Price for this batch', max_digits=14),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='sale_price',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Selling price for this batch', max_digits=14),
        ),
    ]
