# Generated by Django 5.2.4 on 2026-10-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_product_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(default='pcs', max_length=50),
        ),
    ]
