# Generated by Django 5.2.4 on 2026-10-03 14:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_product_unit_free_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item_code',
            field=models.CharField(blank=True, db_index=True, help_text='User-defined unique product code / SKU per business', max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('item_code__isnull', False), models.Q(('item_code', ''), _negated=True)), fields=('created_by', 'item_code'), name='unique_tenant_product_item_code'),
        ),
    ]
