# Generated by Django 5.2.4 on 2026-10-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_product_item_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='internal_reference',
            field=models.CharField(blank=True, db_index=True, help_text='Internal alphanumeric reference code', max_length=100, null=True),
        ),
    ]
