# HR DRF serializers — implemented in tasks 6–14

from rest_framework import serializers

from .models import (
    Department, Designation, Employee, AttendanceRecord,
    LeaveType, LeaveBalance, LeaveApplication,
    SalaryStructure, SalaryComponent, EmployeeSalaryAssignment,
    PayrollRun, Payslip, EmployeeTask, EmployeeQuery, EmployeeNotification
)


class DepartmentSerializer(serializers.ModelSerializer):
    """
    Serializer for Department.
    - id and created_at are read-only (auto-generated by the model)
    - name is writable
    Requirements: 3.1
    """

    class Meta:
        model = Department
        fields = ['id', 'name', 'created_at']
        read_only_fields = ['id', 'created_at']

    def validate_name(self, value):
        request = self.context.get('request')
        if request and hasattr(request, 'user'):
            tenant = getattr(request.user, 'active_tenant', request.user)
            qs = Department.objects.filter(tenant=tenant, name__iexact=value)
            if self.instance:
                qs = qs.exclude(id=self.instance.id)
            if qs.exists():
                raise serializers.ValidationError("A department with this name already exists.")
        return value


class DesignationSerializer(serializers.ModelSerializer):
    """
    Serializer for Designation.
    - id and created_at are read-only (auto-generated by the model)
    - name is writable
    Requirements: 3.2
    """

    class Meta:
        model = Designation
        fields = ['id', 'name', 'created_at']
        read_only_fields = ['id', 'created_at']

    def validate_name(self, value):
        request = self.context.get('request')
        if request and hasattr(request, 'user'):
            tenant = getattr(request.user, 'active_tenant', request.user)
            qs = Designation.objects.filter(tenant=tenant, name__iexact=value)
            if self.instance:
                qs = qs.exclude(id=self.instance.id)
            if qs.exists():
                raise serializers.ValidationError("A designation with this name already exists.")
        return value


class EmployeeSerializer(serializers.ModelSerializer):
    """
    Serializer for Employee profile.
    - Includes department_name and designation_name as read-only fields.
    - employee_code is read-only.
    - Validates that the assigned user (if any) belongs to the same tenant.
    Requirements: 2.1, 2.2, 2.3, 2.4, 7.1
    """
    department_name = serializers.CharField(source='department.name', read_only=True)
    designation_name = serializers.CharField(source='designation.name', read_only=True)

    class Meta:
        model = Employee
        exclude = ['tenant']  # Exclude tenant as it's set by the viewset
        read_only_fields = ['id', 'employee_code', 'created_at', 'updated_at']

    def validate_user(self, value):
        if value:
            request = self.context.get('request')
            if request and hasattr(request, 'user'):
                tenant = getattr(request.user, 'active_tenant', request.user)
                # Check if the user belongs to the same tenant
                user_tenant = getattr(value, 'active_tenant', value)
                if user_tenant != tenant and value != tenant:
                    raise serializers.ValidationError("Assigned user does not belong to the active tenant.")
        return value


class AttendanceRecordSerializer(serializers.ModelSerializer):
    employee_name = serializers.CharField(source='employee.full_name', read_only=True)
    employee_code = serializers.CharField(source='employee.employee_code', read_only=True)

    class Meta:
        model = AttendanceRecord
        exclude = ['tenant']
        read_only_fields = ['id', 'created_at', 'updated_at']
        validators = []  # Disable default UniqueTogetherValidator for upsert

    def validate_employee(self, value):
        request = self.context.get('request')
        if request and hasattr(request, 'user'):
            tenant = getattr(request.user, 'active_tenant', request.user)
            if value.tenant != tenant:
                raise serializers.ValidationError("Employee does not belong to the active tenant.")
        return value


class LeaveTypeSerializer(serializers.ModelSerializer):
    class Meta:
        model = LeaveType
        exclude = ['tenant']
        read_only_fields = ['id', 'created_at', 'updated_at']

    def validate_name(self, value):
        request = self.context.get('request')
        if request and hasattr(request, 'user'):
            tenant = getattr(request.user, 'active_tenant', request.user)
            qs = LeaveType.objects.filter(tenant=tenant, name__iexact=value)
            if self.instance:
                qs = qs.exclude(id=self.instance.id)
            if qs.exists():
                raise serializers.ValidationError("A leave type with this name already exists.")
        return value


class LeaveBalanceSerializer(serializers.ModelSerializer):
    class Meta:
        model = LeaveBalance
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']

    def validate_employee(self, value):
        request = self.context.get('request')
        if request and hasattr(request, 'user'):
            tenant = getattr(request.user, 'active_tenant', request.user)
            if value.tenant != tenant:
                raise serializers.ValidationError("Employee does not belong to the active tenant.")
        return value


class LeaveApplicationSerializer(serializers.ModelSerializer):
    employee_name = serializers.CharField(source='employee.full_name', read_only=True)
    employee_code = serializers.CharField(source='employee.employee_code', read_only=True)
    leave_type_name = serializers.CharField(source='leave_type.name', read_only=True)

    class Meta:
        model = LeaveApplication
        exclude = ['tenant']
        read_only_fields = ['id', 'computed_days', 'lwp_days', 'status', 'applied_at', 'updated_at']

    def validate_employee(self, value):
        request = self.context.get('request')
        if request and hasattr(request, 'user'):
            tenant = getattr(request.user, 'active_tenant', request.user)
            if value.tenant != tenant:
                raise serializers.ValidationError("Employee does not belong to the active tenant.")
        return value

    def validate(self, data):
        start_date = data.get('start_date')
        end_date = data.get('end_date')
        if start_date and end_date and start_date > end_date:
            raise serializers.ValidationError({"end_date": "End date must be after start date."})
        return data


class SalaryComponentSerializer(serializers.ModelSerializer):
    class Meta:
        model = SalaryComponent
        fields = ['id', 'name', 'component_type', 'is_basic', 'value', 'order']


class SalaryStructureSerializer(serializers.ModelSerializer):
    components = SalaryComponentSerializer(many=True)

    class Meta:
        model = SalaryStructure
        exclude = ['tenant']
        read_only_fields = ['id', 'created_at', 'updated_at']

    def validate(self, data):
        components = data.get('components', [])
        basic_count = sum(1 for c in components if c.get('is_basic', False))
        if basic_count != 1:
            raise serializers.ValidationError("Exactly one component must be designated as the Basic component (is_basic=True).")
        return data

    def create(self, validated_data):
        components_data = validated_data.pop('components', [])
        structure = super().create(validated_data)
        for comp in components_data:
            SalaryComponent.objects.create(salary_structure=structure, **comp)
        return structure

    def update(self, instance, validated_data):
        components_data = validated_data.pop('components', None)
        instance = super().update(instance, validated_data)
        
        if components_data is not None:
            instance.components.all().delete()
            for comp in components_data:
                SalaryComponent.objects.create(salary_structure=instance, **comp)
        return instance


from decimal import Decimal

class EmployeeSalaryAssignmentSerializer(serializers.ModelSerializer):
    employee_name = serializers.CharField(source='employee.full_name', read_only=True)
    salary_structure_name = serializers.CharField(source='salary_structure.name', read_only=True)

    class Meta:
        model = EmployeeSalaryAssignment
        exclude = ['tenant']
        read_only_fields = ['id', 'computed_components', 'created_at', 'updated_at']

    def validate_employee(self, value):
        request = self.context.get('request')
        if request and hasattr(request, 'user'):
            tenant = getattr(request.user, 'active_tenant', request.user)
            if value.tenant != tenant:
                raise serializers.ValidationError("Employee does not belong to the active tenant.")
        return value

    def create(self, validated_data):
        assignment = super().create(validated_data)
        self._compute_components(assignment)
        return assignment

    def update(self, instance, validated_data):
        assignment = super().update(instance, validated_data)
        self._compute_components(assignment)
        return assignment

    def _compute_components(self, assignment):
        ctc = assignment.monthly_ctc
        components = assignment.salary_structure.components.all()
        
        basic_comp = next((c for c in components if c.is_basic), None)
        if not basic_comp:
            raise serializers.ValidationError("Salary structure must have a basic component.")
            
        computed = {}
        # Compute basic first
        if basic_comp.component_type == 'fixed':
            basic_value = basic_comp.value
        elif basic_comp.component_type == 'pct_gross':
            basic_value = ctc * (basic_comp.value / Decimal('100.0'))
        else:
            basic_value = ctc * (basic_comp.value / Decimal('100.0'))
            
        for comp in components:
            if comp.component_type == 'fixed':
                val = comp.value
            elif comp.component_type == 'pct_gross':
                val = ctc * (comp.value / Decimal('100.0'))
            elif comp.component_type == 'pct_basic':
                val = basic_value * (comp.value / Decimal('100.0'))
            else:
                val = Decimal('0.0')
                
            computed[comp.name] = str(round(val, 2))
            
        assignment.computed_components = computed
        assignment.save(update_fields=['computed_components'])


class PayrollRunSerializer(serializers.ModelSerializer):
    class Meta:
        model = PayrollRun
        exclude = ['tenant']
        read_only_fields = ['id', 'status', 'total_gross', 'total_net', 'finalised_at', 'created_at', 'updated_at']

    def validate(self, data):
        request = self.context.get('request')
        if request and hasattr(request, 'user'):
            tenant = getattr(request.user, 'active_tenant', request.user)
            # check if an already finalised run exists for this month and year
            month = data.get('month', getattr(self.instance, 'month', None))
            year = data.get('year', getattr(self.instance, 'year', None))
            
            if PayrollRun.objects.filter(tenant=tenant, month=month, year=year, status='finalised').exists():
                raise serializers.ValidationError("A finalised payroll run already exists for this month and year.")
        return data


class PayslipSerializer(serializers.ModelSerializer):
    employee_code = serializers.CharField(source='employee.employee_code', read_only=True)
    employee_name = serializers.CharField(source='employee.full_name', read_only=True)

    class Meta:
        model = Payslip
        exclude = ['tenant']
        read_only_fields = ['id', 'created_at']

class EmployeeTaskSerializer(serializers.ModelSerializer):
    employee_name = serializers.CharField(source='employee.full_name', read_only=True)
    assigned_by_name = serializers.CharField(source='assigned_by.username', read_only=True)

    class Meta:
        model = EmployeeTask
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at', 'assigned_by']

class EmployeeQuerySerializer(serializers.ModelSerializer):
    employee_name = serializers.CharField(source='employee.full_name', read_only=True)
    resolved_by_name = serializers.CharField(source='resolved_by.username', read_only=True)

    class Meta:
        model = EmployeeQuery
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at', 'resolved_by']


class EmployeeNotificationSerializer(serializers.ModelSerializer):
    employee_name = serializers.CharField(source='employee.full_name', read_only=True)
    created_by_name = serializers.CharField(source='created_by.username', read_only=True)

    class Meta:
        model = EmployeeNotification
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'created_by', 'tenant']
