# Generated by Django 5.2.4 on 2026-04-30 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='gstrate',
            new_name='references__rate_5029ce_idx',
            old_name='references_gstrat_rate_idx',
        ),
        migrations.RenameIndex(
            model_name='gstrate',
            new_name='references__categor_e0f501_idx',
            old_name='references_gstrat_categ_idx',
        ),
        migrations.RenameIndex(
            model_name='gstrate',
            new_name='references__slug_39b4e7_idx',
            old_name='references_gstrat_slug_idx',
        ),
        migrations.RenameIndex(
            model_name='hsncode',
            new_name='references__code_fa88be_idx',
            old_name='references_hsnco_code_idx',
        ),
        migrations.RenameIndex(
            model_name='hsncode',
            new_name='references__slug_e0613d_idx',
            old_name='references_hsnco_slug_idx',
        ),
        migrations.RenameIndex(
            model_name='hsncode',
            new_name='references__categor_3e475d_idx',
            old_name='references_hsnco_categ_idx',
        ),
        migrations.AlterField(
            model_name='hsncode',
            name='external_id',
            field=models.CharField(blank=True, help_text='ID from external API source', max_length=100, null=True),
        ),
    ]
